---
title: Mid-Holocene reef defines pristine coral communities in the Caribbean Panama,
  and reveal a bright spot
author: "Lepore M. L., O'Dea A."
date: '`r Sys.Date()`'
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

Pristine ecosystems can help us contextualize and better understand ecological trends and exceptions. We asked what is a "pristine" coral reef, and has been the state of coral reefs over the past several years to decades. Focused on Isla Colon (Caribbean Panama), this study defines "pristine" coral reefs with mid-Holocene communities of reef corals (~6,500 years old)--exposed to negligible human impact--and tests if subrecent communities (few years-decades old) fit that definition or are degraded. Our results confirm the Caribbean-wide pattern of coral reefs' decline, but reveal one reef that fits our pragmatic definition of "pristine", Punta Caracol. Like mid-Holocene reefs and unlike other subrecent reefs, Punta Caracol was dominated by _Acropora cervicornis_ corals, that are now almost extinct in the Caribbean. After we excluded _A. cervicornis_, however, Punta Caracol still differed from other subrecent reefs. This study illustrates an approach to evaluate human impact on ecosystems that fossilize well, such as coral reefs, and sets the road to reveal positive deviations (bright spots) among otherwise declining ecosystem patches, and to learn why such deviations are possible...

This seems incomplete!
