---
title: "rpubs.com/forestgeo/gh2"
subtitle: "GitHub Tutorial 2"
author: "maurolepore@gmail.com"
date: "25 July 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Recap GitHub tutorial 1 | Have you accepted the invitation to github.com/forestgeo?

# Goal | Interact with GitHub from RStudio

Requisites ([Initial Set up](https://github.com/forestgeo/learn/issues/31))

- GitHub account.
- Git installed in your computer.
- RStudio installed in your computer.

## Catching up | If you get lost, don't worry!

You can catch up later by asking me or reading:

- Slides. Why and how to use git: [Git for Humans](https://speakerdeck.com/alicebartlett/git-for-humans)
- Book chapter. Initial setup and overview: http://r-pkgs.had.co.nz/git.html. 
- Book. All, with a friendly style: http://happygitwithr.com/

- tutorials/articles/Learning_road_map.docx

__Haven't installled git yet? Sit next to someone that has it.__

## Motivation | Why using git?

- [With dropbox](https://speakerdeck.com/alicebartlett/git-for-humans?slide=22)

- With Git

    - [Express why things change](https://speakerdeck.com/alicebartlett/git-for-humans?slide=36)

    - [Try new things savely](https://speakerdeck.com/alicebartlett/git-for-humans?slide=64)
    
    - [Collaborate](https://speakerdeck.com/alicebartlett/git-for-humans?slide=75)

## How you can use git | Here we will use RStudio.

- **From RStudio.**

- **From a GUI* (
[Recommended Git clients](http://happygitwithr.com/git-client.html#recommended-git-clients)).**

- **From a shell such as bash. **

## Hands on


- Touch base by giving hands up on [this issue](https://github.com/forestgeo/tutorials/issues/1)
How many people installed git?

## Open a repo

## Delete a repo

## Open another repo

### Upload a text file.

### Edit the file

### Download the file

## Clone a repo

### Open a new repo on GitHub.

### Write a readme file.

### Then clone the repo into an RStudio project.


### Change something, on the read me file; ten revert the changes.

### Change something else; then commit the changes.

### Explore history.

### Push 

## Fork

### Fork forestr/tutorials into your \<your-account\>/tutorials.

### Clone forestr/tutorials into an RStudio project.

### Change something locally, e.g. README. Then push.

### Confirm the change in your fork.

## Pull request

### Request to pull your your fork into forestr/tutorials

## Upload an existing projec

### In your account, name a new repo as in your computer

### Follow instructions from GitHub (require the shell)

#

end. 
























